name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build&Push
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Get repository info
        uses: gacts/github-slug@v1
        id: slug
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/githubactions:${{ steps.slug.outputs.commit-hash-short }}
          
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: tale/kubectl-action@v1
  #     with:
  #       base64-kube-config: ${{ secrets.KUBE_CONFIG }}
  #   - run: kubectl set image deployment/front-end mycontainer=myimage:latest